apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lucas-docs
  namespace: a2w-lucas
spec:
  rules:
    - host: docs.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lucas-docs
                port:
                  number: 80
